# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  database: bingbong_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bingbong_test
  pool: 5
  timeout: 5000
